### ISSUE TITLE
Changes to home page

### ISSUE THREAD

**Issue by Saf456** [AscentMS/NHSD#102]
[Alt version of GPOS screen.docx](https://github.com/AscentMS/NHSD/files/1231624/Alt.version.of.GPOS.screen.docx)

Ben changes attached in M.word, you will need to change the formatting to match whats already there. Key is making sure the bold text visible and stands out. 

Can you do this in the test version first so the team can check. 
thank you

**Comment by Seahermit** [comment]
Looks like this now...

<img width="574" alt="screen shot 2017-08-17 at 17 56 26" src="https://user-images.githubusercontent.com/10967025/29423949-9730036c-8375-11e7-9f5a-9a5c6ac7826f.png">

I don't like the CLICK HERE bit - I thought we'd stopped doing that these days due to lack of context?  But if that's what you want, that's what you'll get!
