### ISSUE TITLE
Signup page styling

### ISSUE THREAD

**Issue by gordonss** [AscentMS/NHSD#74]
Maybe it's just me, but the signup page seems to lack some elements of visual styling - in another issue I mention the font for the title, but I think there is a bit more? Certainly the 'Need Help' link at top-right does not look styled correctly

**Comment by ballzy** [comment]
This page is ok. Styled fine. The main difference is that it doesn't have the top blue bar. We are only working with the tools that we are faced with.

The Need Help link could be a touch smaller maybe. 16px instead of 19px. But it is a generic style associated to all a tags inside an H1. Maybe we could do: 

.signup h1 a { font-size: 16px; } 

@Seahermit could you try dropping in this css - thanks

**Comment by Seahermit** [comment]
Done
