### ISSUE TITLE
[Remove Security Question] is removing the wrong question

### ISSUE THREAD

**Issue by andrewleponis** [AscentMS/NHSD#94]
When logging in and going directly to the Security questions page, and clicking remove on the last question, the first question is deleted.

1. Add a second and third Security Question
2. Log out of GP Online
3. Log back in and go directly to  [Change Security Question]
4. Remove the last Security Question.

Result:- the first security question removed.

**Comment by Saf456** [comment]
I have replicated this and yes the same happened to me. I set up 4 security questions, logged out and logged back in, I went back to delete a third security question and it deleted the wrong one.

**Comment by Seahermit** [comment]
This was a very good find - it's happening on our live version as well, so thank-you for finding it!  Was slightly complicated, and a byproduct is now the security questions are in alphabetical order, so a bit easier to find a particular question (although that might just because I know what all the questions are by heart now)

**Comment by Saf456** [comment]
tested - now works as should
